packages:
  - 'apps/*'
  - 'packages/*'

# PNPM Catalog for centralized dependency management
catalog:
  # Core Dependencies
  react: ^18.3.1
  react-dom: ^18.3.1
  next: ^15.1.3

  # TypeScript & Build Tools
  typescript: ^5.8.3
  tsup: ^8.5.0
  '@types/node': ^24.0.14
  '@types/react': ^19.1.8

  # Testing
  vitest: ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@testing-library/react': ^16.1.0
  '@testing-library/jest-dom': ^6.6.3
  '@vitejs/plugin-react': ^4.2.0
  jsdom: ^26.1.0

  # Linting & Formatting
  eslint: ^9.17.0
  '@eslint/js': ^9.17.0
  '@typescript-eslint/eslint-plugin': ^8.17.0
  '@typescript-eslint/parser': ^8.17.0
  eslint-plugin-turbo: ^2.5.5
  prettier: ^3.4.2

  # Infrastructure
  sst: ^3.17.10
  '@types/aws-lambda': ^8.10.150

  # Utilities
  zod: ^3.23.8